---@class CodeGenConfig 代码生成配置
local GenerateHotfixCodeConfig = {
    --- 热更代码配置
    --- 热更层命名空间
    HotfixNameSpace = "ET",
    --- 热更层代码输出目录
    HotfixCodeOutPutPath = "../../Unity/Assets/ModelView/Demo/FGUI/AutoGeneratedCode/",

    --- 非热更代码配置
    --- 非热更层命名空间
    ModelNameSpace = "ET",
    --- 非热更层代码输出目录
    ModelCodeOutPutPath = "../../Unity/Assets/Mono/Demo/AutoGeneratedCode/",
}

return GenerateHotfixCodeConfig